name = "tr4c3-twitter-bot"
main = "worker.js"
compatibility_date = "2024-01-01"

# Cron Trigger - Runs every 10 minutes
[triggers]
crons = [
  "*/10 * * * *"  # Every 10 minutes
]

# Secrets (add via CLI or Cloudflare Dashboard)
# Don't put actual values here - use: wrangler secret put <NAME>
# Or add via Cloudflare Dashboard: Workers > tr4c3-twitter-bot > Settings > Variables

# Required secrets:
# - OPENAI_API_KEY
# - TWITTER_API_KEY
# - TWITTER_API_SECRET
# - TWITTER_ACCESS_TOKEN
# - TWITTER_ACCESS_SECRET
